version: '2'
services:
  centos6:
    image: centos_openldap:6
    build: ./centos6
    hostname: centos6
    tty: true
    volumes:
      - './centos6/home/:/home/:rw'
      - './centos6/opt/openldap/:/opt/openldap/:rw'
      - '../scripts/:/opt/openldap/workspace/scripts/:rw'
      - '../archives/:/opt/openldap/workspace/archives/:rw'
  ubuntu1404:
    image: ubuntu_openldap:14.08
    build: ./ubuntu1404
    hostname: ubuntu1404
    tty: true
    volumes:
      - './ubuntu1404/home/:/home/:rw'
      - './ubuntu1404/opt/openldap/:/opt/openldap/:rw'
      - '../scripts/:/opt/openldap/workspace/scripts/:rw'
      - '../archives/:/opt/openldap/workspace/archives/:rw'
