version: '2'
services:
  centos6:
    build: ./centos6
    hostname: centos6
    tty: true
    volumes:
      - './centos6/home/:/home/:rw'
      - './centos6/usr/local/:/usr/local/:rw'
      - '../scripts/:/usr/local/workspace/scripts/:rw'
      - '../archives/:/usr/local/workspace/archives/:rw'
  centos7:
    build: ./centos7
    hostname: centos7
    tty: true
    volumes:
      - './centos7/home/:/home/:rw'
      - './centos7/usr/local/:/usr/local/:rw'
      - '../scripts/:/usr/local/workspace/scripts/:rw'
      - '../archives/:/usr/local/workspace/archives/:rw'
  ubuntu1404:
    build: ./ubuntu1404
    hostname: ubuntu1404
    tty: true
    volumes:
      - './ubuntu1404/home/:/home/:rw'
      - './ubuntu1404/usr/local/:/usr/local/:rw'
      - '../scripts/:/usr/local/workspace/scripts/:rw'
      - '../archives/:/usr/local/workspace/archives/:rw'
  ubuntu1604:
    build: ./ubuntu1604
    hostname: ubuntu1604
    tty: true
    volumes:
      - './ubuntu1604/home/:/home/:rw'
      - './ubuntu1604/usr/local/:/usr/local/:rw'
      - '../scripts/:/usr/local/workspace/scripts/:rw'
      - '../archives/:/usr/local/workspace/archives/:rw'
